name: Deploy to GCP
on:
  workflow_dispatch:
env:
  IMAGE: europe-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/web/k33-web-gateway/nginx:1.25.1-alpine
jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v3
      - name: Google auth
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      - name: Authorize Docker push
        run: gcloud auth configure-docker europe-docker.pkg.dev
      - name: Push image to gcp artifact registry
        run: |-
          docker image build -t "$IMAGE" config
          docker image push "$IMAGE"
      - name: Deploy to GCP Cloud Run
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          DEFAULT_HOSTNAME: ${{ secrets.DEFAULT_HOSTNAME }}
          RESEARCH_HOSTNAME: ${{ secrets.RESEARCH_HOSTNAME }}
          RESEARCH_ARCHIVE_HOSTNAME: ${{ secrets.RESEARCH_ARCHIVE_HOSTNAME }}
          INVEST_HOSTNAME: ${{ secrets.INVEST_HOSTNAME }}
          AUTH_HOSTNAME: ${{ secrets.AUTH_HOSTNAME }}
        run: |-
          gcloud run deploy k33-web-gateway \
            --region europe-west1 \
            --image "$IMAGE" \
            --cpu=1 \
            --memory=512Mi \
            --min-instances=1 \
            --max-instances=1 \
            --concurrency=1000 \
            --set-env-vars=DEFAULT_HOSTNAME="$DEFAULT_HOSTNAME" \
            --set-env-vars=RESEARCH_HOSTNAME="$RESEARCH_HOSTNAME" \
            --set-env-vars=RESEARCH_ARCHIVE_HOSTNAME="$RESEARCH_ARCHIVE_HOSTNAME" \
            --set-env-vars=INVEST_HOSTNAME="$INVEST_HOSTNAME" \
            --set-env-vars=AUTH_HOSTNAME="$AUTH_HOSTNAME" \
            --set-env-vars=WEB_DOMAIN_NAME=k33.com \
            --set-env-vars=NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx/ \
            --service-account k33-web-gateway@"$GCP_PROJECT_ID".iam.gserviceaccount.com \
            --allow-unauthenticated \
            --ingress=internal-and-cloud-load-balancing \
            --port=8080 \
            --platform=managed
